#! /bin/sh
chmod -x img/*.jpg img/weather/*.jpg *.pdf *.ltx xepersian.dtx
xelatex -shell-escape xepersian.dtx
xelatex -shell-escape xepersian.dtx
xelatex -shell-escape xepersian.dtx
teckit_compile persian-tex-text.map
teckit_compile persian-tex-text.map
teckit_compile persian-tex-text.map
teckit_compile persian-tex-text-nonumbers.map
teckit_compile persian-tex-text-nonumbers.map
teckit_compile persian-tex-text-nonumbers.map
xelatex -shell-escape xepersian-doc.ltx
xelatex -shell-escape xepersian-doc.ltx
xelatex -shell-escape xepersian-doc.ltx
mkdir -p doc/latex/xepersian fonts/misc/xetex/fontmapping/xepersian source/latex/xepersian tex/latex/xepersian 
mkdir xepersian
mv *.def *.lua *.sty *.cls  xepersian-logo.pdf tex/latex/xepersian
mv *.ltx *.dtx *.ins source/latex/xepersian
mv *.pdf *.py *.tex README img doc/latex/xepersian
mv persian-tex-text.map persian-tex-text.tec persian-tex-text-nonumbers.map persian-tex-text-nonumbers.tec fonts/misc/xetex/fontmapping/xepersian
zip -r xepersiantds doc/latex/xepersian fonts/misc/xetex/fontmapping/xepersian source/latex/xepersian tex/latex/xepersian
mv xepersiantds.zip xepersian.tds.zip
mv doc/latex/xepersian/*.pdf doc/latex/xepersian/*.py doc/latex/xepersian/README  doc/latex/xepersian/img source/latex/xepersian/*.ltx source/latex/xepersian/*.dtx xepersian
zip -r xepersian xepersian.tds.zip xepersian
rm -r doc tex source fonts xepersian
rm *.aux *.hd *.idx *.ilg *.ind *.log *.out *.toc xepersian.tds.zip



